<?php
/**
 * Display Settings Configuration
 *
 * Defines all display-related settings for the weather widget
 * including regional preferences, current weather, additional data,
 * forecast data, and footer settings.
 *
 * @package    PearlWeather
 * @subpackage PearlWeather/Admin/Config
 * @since      1.0.0
 */

namespace PearlWeather\Admin\Config;

// Prevent direct access.
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

use PearlWeather\Framework\Framework;

/**
 * Register Display Settings Section
 */
Framework::create_section(
	'pw_weather_generator',
	array(
		'title'  => __( 'Display Settings', 'pearl-weather' ),
		'icon'   => '<span><i class="pw-icon-display"></i></span>',
		'fields' => array(
			array(
				'type'  => 'tabbed',
				'class' => 'pw-display-tabs',
				'tabs'  => array(
					// Tab 1: Regional Preferences.
					array(
						'title'  => __( 'Regional Preferences', 'pearl-weather' ),
						'icon'   => '<span><i class="pw-icon-regional"></i></span>',
						'fields' => array(
							array(
								'id'         => 'show_title',
								'type'       => 'switcher',
								'title'      => __( 'Weather Section Title', 'pearl-weather' ),
								'class'      => 'pw-first-fields',
								'default'    => true,
								'text_on'    => __( 'Show', 'pearl-weather' ),
								'text_off'   => __( 'Hide', 'pearl-weather' ),
								'text_width' => 75,
							),
							array(
								'id'         => 'show_location_name',
								'type'       => 'switcher',
								'title'      => __( 'Location Name', 'pearl-weather' ),
								'default'    => true,
								'text_on'    => __( 'Show', 'pearl-weather' ),
								'text_off'   => __( 'Hide', 'pearl-weather' ),
								'text_width' => 75,
							),
							array(
								'id'         => 'show_current_date',
								'type'       => 'switcher',
								'title'      => __( 'Current Date', 'pearl-weather' ),
								'default'    => true,
								'text_on'    => __( 'Show', 'pearl-weather' ),
								'text_off'   => __( 'Hide', 'pearl-weather' ),
								'text_width' => 75,
							),
							array(
								'id'         => 'date_format',
								'type'       => 'select',
								'title'      => __( 'Date Format', 'pearl-weather' ),
								'title_info' => '<div class="pw-info-label">' . __( 'Date Format', 'pearl-weather' ) . '</div><div class="pw-short-content">' . __( 'Choose the most common date format for your visitors.', 'pearl-weather' ) . '</div>',
								'options'    => array(
									'M j, Y' => date_i18n( 'M j, Y' ) . ' (M j, Y)',
									'F j, Y' => date_i18n( 'F j, Y' ) . ' (F j, Y)',
									'Y-m-d'  => date_i18n( 'Y-m-d' ) . ' (Y-m-d)',
									'm/d/Y'  => date_i18n( 'm/d/Y' ) . ' (m/d/Y)',
									'd/m/Y'  => date_i18n( 'd/m/Y' ) . ' (d/m/Y)',
									'custom' => __( 'Custom', 'pearl-weather' ),
								),
								'default'    => 'M j, Y',
								'dependency' => array( 'show_current_date', '==', 'true' ),
							),
							array(
								'id'         => 'custom_date_format',
								'type'       => 'text',
								'class'      => 'pw-custom-date-format',
								'title'      => ' ',
								'default'    => 'F j, Y',
								'dependency' => array( 'show_current_date|date_format', '==|==', 'true|custom' ),
							),
							array(
								'id'         => 'show_current_time',
								'type'       => 'switcher',
								'title'      => __( 'Current Time', 'pearl-weather' ),
								'default'    => true,
								'text_on'    => __( 'Show', 'pearl-weather' ),
								'text_off'   => __( 'Hide', 'pearl-weather' ),
								'text_width' => 75,
							),
							array(
								'id'         => 'time_format',
								'class'      => 'pw-time-format',
								'type'       => 'select',
								'title'      => __( 'Time Format', 'pearl-weather' ),
								'options'    => array(
									'g:i a' => gmdate( 'g:i a', time() ) . ' (g:i a)',
									'g:i A' => gmdate( 'g:i A', time() ) . ' (g:i A)',
									'H:i'   => gmdate( 'H:i', time() ) . ' (H:i)',
								),
								'default'    => 'g:i a',
								'dependency' => array( 'show_current_time', '==', 'true' ),
							),
							array(
								'id'         => 'timezone',
								'type'       => 'select',
								'title'      => __( 'Time Zone', 'pearl-weather' ),
								'options'    => array(
									''          => __( 'Default (auto-detected)', 'pearl-weather' ),
									'UTC-12'    => 'UTC-12',
									'UTC-11'    => 'UTC-11',
									'UTC-10'    => 'UTC-10',
									'UTC-9'     => 'UTC-9',
									'UTC-8'     => 'UTC-8',
									'UTC-7'     => 'UTC-7',
									'UTC-6'     => 'UTC-6',
									'UTC-5'     => 'UTC-5',
									'UTC-4'     => 'UTC-4',
									'UTC-3'     => 'UTC-3',
									'UTC-2'     => 'UTC-2',
									'UTC-1'     => 'UTC-1',
									'UTC+0'     => 'UTC+0',
									'UTC+1'     => 'UTC+1',
									'UTC+2'     => 'UTC+2',
									'UTC+3'     => 'UTC+3',
									'UTC+4'     => 'UTC+4',
									'UTC+5'     => 'UTC+5',
									'UTC+5:30'  => 'UTC+5:30',
									'UTC+6'     => 'UTC+6',
									'UTC+7'     => 'UTC+7',
									'UTC+8'     => 'UTC+8',
									'UTC+9'     => 'UTC+9',
									'UTC+10'    => 'UTC+10',
									'UTC+11'    => 'UTC+11',
									'UTC+12'    => 'UTC+12',
								),
								'default'    => '',
								'title_info' => '<div class="pw-info-label">' . __( 'Time Zone', 'pearl-weather' ) . '</div><div class="pw-short-content">' . __( 'Recommended to use Default (auto-detected).', 'pearl-weather' ) . '</div>',
							),
							array(
								'id'         => 'language',
								'type'       => 'select',
								'title'      => __( 'Language', 'pearl-weather' ),
								'title_info' => '<div class="pw-info-label">' . __( 'OpenWeatherMap Language', 'pearl-weather' ) . '</div><div class="pw-short-content">' . __( 'Language for OpenWeatherMap data.', 'pearl-weather' ) . '</div>',
								'options'    => array(
									'en'    => __( 'English', 'pearl-weather' ),
									'ar'    => __( 'Arabic', 'pearl-weather' ),
									'bg'    => __( 'Bulgarian', 'pearl-weather' ),
									'ca'    => __( 'Catalan', 'pearl-weather' ),
									'cz'    => __( 'Czech', 'pearl-weather' ),
									'da'    => __( 'Danish', 'pearl-weather' ),
									'de'    => __( 'German', 'pearl-weather' ),
									'el'    => __( 'Greek', 'pearl-weather' ),
									'es'    => __( 'Spanish', 'pearl-weather' ),
									'fi'    => __( 'Finnish', 'pearl-weather' ),
									'fr'    => __( 'French', 'pearl-weather' ),
									'he'    => __( 'Hebrew', 'pearl-weather' ),
									'hi'    => __( 'Hindi', 'pearl-weather' ),
									'hr'    => __( 'Croatian', 'pearl-weather' ),
									'hu'    => __( 'Hungarian', 'pearl-weather' ),
									'id'    => __( 'Indonesian', 'pearl-weather' ),
									'it'    => __( 'Italian', 'pearl-weather' ),
									'ja'    => __( 'Japanese', 'pearl-weather' ),
									'kr'    => __( 'Korean', 'pearl-weather' ),
									'nl'    => __( 'Dutch', 'pearl-weather' ),
									'no'    => __( 'Norwegian', 'pearl-weather' ),
									'pl'    => __( 'Polish', 'pearl-weather' ),
									'pt'    => __( 'Portuguese', 'pearl-weather' ),
									'ro'    => __( 'Romanian', 'pearl-weather' ),
									'ru'    => __( 'Russian', 'pearl-weather' ),
									'sv'    => __( 'Swedish', 'pearl-weather' ),
									'th'    => __( 'Thai', 'pearl-weather' ),
									'tr'    => __( 'Turkish', 'pearl-weather' ),
									'uk'    => __( 'Ukrainian', 'pearl-weather' ),
									'vi'    => __( 'Vietnamese', 'pearl-weather' ),
									'zh_cn' => __( 'Chinese Simplified', 'pearl-weather' ),
									'zh_tw' => __( 'Chinese Traditional', 'pearl-weather' ),
								),
								'default'    => 'en',
							),
							array(
								'id'         => 'show_preloader',
								'type'       => 'switcher',
								'title'      => __( 'Preloader', 'pearl-weather' ),
								'default'    => true,
								'text_on'    => __( 'Enabled', 'pearl-weather' ),
								'text_off'   => __( 'Disabled', 'pearl-weather' ),
								'text_width' => 94,
							),
						),
					),
					// Tab 2: Current Weather.
					array(
						'title'  => __( 'Current Weather', 'pearl-weather' ),
						'icon'   => '<span><i class="pw-icon-current"></i></span>',
						'fields' => array(
							array(
								'id'         => 'show_weather_icon',
								'type'       => 'switcher',
								'title'      => __( 'Weather Condition Icon', 'pearl-weather' ),
								'default'    => true,
								'text_on'    => __( 'Show', 'pearl-weather' ),
								'text_off'   => __( 'Hide', 'pearl-weather' ),
								'text_width' => 75,
							),
							array(
								'id'               => 'current_icon_type',
								'class'            => 'pw-current-icon-type',
								'preview'          => true,
								'type'             => 'select',
								'title'            => __( 'Icon Type', 'pearl-weather' ),
								'options'          => array(
									'icon_set_one'   => __( 'Animated', 'pearl-weather' ),
									'icon_set_two'   => __( 'Static', 'pearl-weather' ),
									'icon_set_three' => __( 'Light Line', 'pearl-weather' ),
									'icon_set_four'  => __( 'Fill', 'pearl-weather' ),
									'icon_set_five'  => __( 'Glassmorphism', 'pearl-weather' ),
								),
								'title_info'       => '<div class="pw-info-label">' . __( 'Icon Type', 'pearl-weather' ) . '</div><div class="pw-short-content">' . __( 'Choose an icon set for current weather display.', 'pearl-weather' ) . '</div>',
								'default'          => 'icon_set_one',
								'dependency'       => array( 'show_weather_icon', '==', 'true' ),
							),
							array(
								'id'         => 'current_icon_size',
								'type'       => 'spinner',
								'class'      => 'pw-current-icon-size',
								'title'      => __( 'Icon Size', 'pearl-weather' ),
								'unit'       => __( 'px', 'pearl-weather' ),
								'max'        => 300,
								'min'        => 16,
								'default'    => 58,
								'dependency' => array( 'show_weather_icon', '==', 'true' ),
							),
							array(
								'id'         => 'show_temperature',
								'type'       => 'switcher',
								'title'      => __( 'Temperature', 'pearl-weather' ),
								'default'    => true,
								'text_on'    => __( 'Show', 'pearl-weather' ),
								'text_off'   => __( 'Hide', 'pearl-weather' ),
								'text_width' => 75,
							),
							array(
								'id'         => 'show_high_low_temp',
								'class'      => 'pw-show-hide',
								'type'       => 'switcher',
								'title'      => __( 'High & Low Temperature', 'pearl-weather' ),
								'default'    => true,
								'text_on'    => __( 'Show', 'pearl-weather' ),
								'text_off'   => __( 'Hide', 'pearl-weather' ),
								'text_width' => 75,
							),
							array(
								'id'         => 'show_feels_like',
								'class'      => 'pw-show-hide',
								'type'       => 'switcher',
								'title'      => __( 'Real Feel', 'pearl-weather' ),
								'default'    => true,
								'text_on'    => __( 'Show', 'pearl-weather' ),
								'text_off'   => __( 'Hide', 'pearl-weather' ),
								'text_width' => 75,
							),
							array(
								'id'         => 'show_weather_description',
								'type'       => 'switcher',
								'title'      => __( 'Weather Condition Description', 'pearl-weather' ),
								'default'    => true,
								'text_on'    => __( 'Show', 'pearl-weather' ),
								'text_off'   => __( 'Hide', 'pearl-weather' ),
								'text_width' => 75,
							),
							array(
								'type'    => 'notice',
								'style'   => 'info',
								'content' => sprintf(
									/* translators: %s: upgrade link */
									__( 'To show more weather details & stylish icons, %sUpgrade to Pro!%s', 'pearl-weather' ),
									'<a href="https://pearlweather.com/pricing/" target="_blank"><strong>',
									'</strong></a>'
								),
							),
						),
					),
					// Tab 3: Additional Data.
					array(
						'title'  => __( 'Additional Data', 'pearl-weather' ),
						'icon'   => '<span><i class="pw-icon-additional"></i></span>',
						'fields' => array(
							array(
								'id'         => 'show_pressure',
								'type'       => 'switcher',
								'title'      => __( 'Pressure', 'pearl-weather' ),
								'title_info' => '<div class="pw-info-label">' . __( 'Atmospheric Pressure', 'pearl-weather' ) . '</div>',
								'default'    => true,
								'text_on'    => __( 'Show', 'pearl-weather' ),
								'text_off'   => __( 'Hide', 'pearl-weather' ),
								'text_width' => 75,
							),
							array(
								'id'         => 'show_humidity',
								'type'       => 'switcher',
								'title'      => __( 'Humidity', 'pearl-weather' ),
								'default'    => true,
								'text_on'    => __( 'Show', 'pearl-weather' ),
								'text_off'   => __( 'Hide', 'pearl-weather' ),
								'text_width' => 75,
							),
							array(
								'id'         => 'show_wind',
								'type'       => 'switcher',
								'title'      => __( 'Wind', 'pearl-weather' ),
								'default'    => true,
								'text_on'    => __( 'Show', 'pearl-weather' ),
								'text_off'   => __( 'Hide', 'pearl-weather' ),
								'text_width' => 75,
							),
							array(
								'id'         => 'show_wind_gust',
								'type'       => 'switcher',
								'title'      => __( 'Wind Gust', 'pearl-weather' ),
								'default'    => true,
								'text_on'    => __( 'Show', 'pearl-weather' ),
								'text_off'   => __( 'Hide', 'pearl-weather' ),
								'text_width' => 75,
							),
							array(
								'id'         => 'show_clouds',
								'type'       => 'switcher',
								'title'      => __( 'Clouds', 'pearl-weather' ),
								'default'    => true,
								'text_on'    => __( 'Show', 'pearl-weather' ),
								'text_off'   => __( 'Hide', 'pearl-weather' ),
								'text_width' => 75,
							),
							array(
								'id'         => 'show_visibility',
								'type'       => 'switcher',
								'title'      => __( 'Visibility', 'pearl-weather' ),
								'default'    => true,
								'text_on'    => __( 'Show', 'pearl-weather' ),
								'text_off'   => __( 'Hide', 'pearl-weather' ),
								'text_width' => 75,
							),
							array(
								'id'         => 'show_sunrise_sunset',
								'type'       => 'switcher',
								'title'      => __( 'Sunrise & Sunset', 'pearl-weather' ),
								'default'    => true,
								'text_on'    => __( 'Show', 'pearl-weather' ),
								'text_off'   => __( 'Hide', 'pearl-weather' ),
								'text_width' => 75,
							),
							array(
								'type'    => 'notice',
								'style'   => 'info',
								'content' => sprintf(
									/* translators: %s: upgrade link */
									__( 'To gain access to additional weather data (UV Index, Dew Point, Air Quality, Moon Phase, etc.), %sUpgrade to Pro!%s', 'pearl-weather' ),
									'<a href="https://pearlweather.com/pricing/" target="_blank"><strong>',
									'</strong></a>'
								),
							),
						),
					),
					// Tab 4: Additional Data Styles.
					array(
						'title'  => __( 'Additional Data Styles', 'pearl-weather' ),
						'icon'   => '<span><i class="pw-icon-additional-style"></i></span>',
						'fields' => array(
							array(
								'id'         => 'additional_data_layout',
								'class'      => 'pw-additional-data-layout',
								'type'       => 'image_select',
								'title'      => __( 'Additional Data Layout', 'pearl-weather' ),
								'options'    => array(
									'center'    => array(
										'image' => Framework::get_url( 'assets/images/layouts/list-center.svg' ),
										'name'  => __( 'List Center', 'pearl-weather' ),
									),
									'left'      => array(
										'image' => Framework::get_url( 'assets/images/layouts/list-left.svg' ),
										'name'  => __( 'List Left', 'pearl-weather' ),
									),
									'justified' => array(
										'image' => Framework::get_url( 'assets/images/layouts/list-justified.svg' ),
										'name'  => __( 'List Justified', 'pearl-weather' ),
									),
								),
								'title_info' => '<div class="pw-info-label">' . __( 'Additional Data Layout', 'pearl-weather' ) . '</div><div class="pw-short-content">' . __( 'Choose how additional weather data is displayed.', 'pearl-weather' ) . '</div>',
								'default'    => 'center',
							),
							array(
								'id'         => 'show_additional_icons',
								'type'       => 'switcher',
								'class'      => 'pw-show-icons',
								'title'      => __( 'Display Icons', 'pearl-weather' ),
								'default'    => true,
								'text_on'    => __( 'Show', 'pearl-weather' ),
								'text_off'   => __( 'Hide', 'pearl-weather' ),
								'text_width' => 75,
							),
							array(
								'id'         => 'additional_icon_type',
								'class'      => 'pw-additional-icon-type',
								'preview'    => true,
								'type'       => 'select',
								'title'      => __( 'Icon Type', 'pearl-weather' ),
								'options'    => array(
									'icon_set_one'   => __( 'Regular', 'pearl-weather' ),
									'icon_set_two'   => __( 'Fill', 'pearl-weather' ),
									'icon_set_three' => __( 'Light', 'pearl-weather' ),
									'icon_set_four'  => __( 'Light 2', 'pearl-weather' ),
								),
								'default'    => 'icon_set_one',
								'dependency' => array( 'show_additional_icons', '==', 'true' ),
							),
							array(
								'id'         => 'additional_icon_color',
								'type'       => 'color_group',
								'title'      => __( 'Icon Color', 'pearl-weather' ),
								'options'    => array(
									'color' => __( 'Color', 'pearl-weather' ),
								),
								'default'    => array(
									'color' => '#ffffff',
								),
								'dependency' => array( 'show_additional_icons', '==', 'true' ),
							),
							array(
								'id'      => 'additional_data_margin',
								'type'    => 'spacing',
								'class'   => 'pw-additional-data-margin',
								'title'   => __( 'Margin', 'pearl-weather' ),
								'units'   => array( 'px' ),
								'right'   => false,
								'left'    => false,
								'default' => array(
									'top'    => '8',
									'bottom' => '3',
								),
							),
							array(
								'id'         => 'additional_icon_size',
								'class'      => 'pw-additional-icon-size',
								'type'       => 'spinner',
								'title'      => __( 'Icon Size', 'pearl-weather' ),
								'unit'       => __( 'px', 'pearl-weather' ),
								'max'        => 300,
								'min'        => 8,
								'default'    => 16,
								'dependency' => array( 'show_additional_icons', '==', 'true' ),
							),
							array(
								'type'    => 'notice',
								'style'   => 'info',
								'class'   => 'pw-notice-padding',
								'content' => sprintf(
									/* translators: %s: upgrade link */
									__( 'To unlock carousel layouts and more styling options, %sUpgrade to Pro!%s', 'pearl-weather' ),
									'<a href="https://pearlweather.com/pricing/" target="_blank"><strong>',
									'</strong></a>'
								),
							),
						),
					),
					// Tab 5: Forecast Data.
					array(
						'title'  => __( 'Forecast Data', 'pearl-weather' ),
						'icon'   => '<span><i class="pw-icon-forecast"></i></span>',
						'fields' => array(
							array(
								'id'         => 'enable_forecast',
								'type'       => 'switcher',
								'title'      => __( 'Enable Weather Forecast', 'pearl-weather' ),
								'default'    => true,
								'text_on'    => __( 'Enabled', 'pearl-weather' ),
								'text_off'   => __( 'Disabled', 'pearl-weather' ),
								'text_width' => 94,
								'title_info' => '<div class="pw-info-label">' . __( 'Enable Weather Forecast', 'pearl-weather' ) . '</div>',
							),
							array(
								'id'         => 'forecast_data_sortable',
								'type'       => 'sortable',
								'title'      => __( 'Forecast Data', 'pearl-weather' ),
								'class'      => 'pw-forecast-sortable',
								'dependency' => array( 'enable_forecast', '==', 'true' ),
								'default'    => array(
									'temperature'   => true,
									'precipitation' => true,
									'rain_chance'   => true,
									'wind'          => true,
									'humidity'      => true,
									'pressure'      => true,
									'snow'          => false,
								),
								'fields'     => array(
									array(
										'id'         => 'temperature',
										'type'       => 'switcher',
										'title'      => __( 'Temperature', 'pearl-weather' ),
										'text_on'    => __( 'Show', 'pearl-weather' ),
										'text_off'   => __( 'Hide', 'pearl-weather' ),
										'text_width' => 75,
									),
									array(
										'id'         => 'precipitation',
										'type'       => 'switcher',
										'title'      => __( 'Precipitation', 'pearl-weather' ),
										'text_on'    => __( 'Show', 'pearl-weather' ),
										'text_off'   => __( 'Hide', 'pearl-weather' ),
										'text_width' => 75,
									),
									array(
										'id'         => 'rain_chance',
										'type'       => 'switcher',
										'title'      => __( 'Rain Chance', 'pearl-weather' ),
										'text_on'    => __( 'Show', 'pearl-weather' ),
										'text_off'   => __( 'Hide', 'pearl-weather' ),
										'text_width' => 75,
									),
									array(
										'id'         => 'wind',
										'type'       => 'switcher',
										'title'      => __( 'Wind', 'pearl-weather' ),
										'text_on'    => __( 'Show', 'pearl-weather' ),
										'text_off'   => __( 'Hide', 'pearl-weather' ),
										'text_width' => 75,
									),
									array(
										'id'         => 'humidity',
										'type'       => 'switcher',
										'title'      => __( 'Humidity', 'pearl-weather' ),
										'text_on'    => __( 'Show', 'pearl-weather' ),
										'text_off'   => __( 'Hide', 'pearl-weather' ),
										'text_width' => 75,
									),
									array(
										'id'         => 'pressure',
										'type'       => 'switcher',
										'title'      => __( 'Pressure', 'pearl-weather' ),
										'text_on'    => __( 'Show', 'pearl-weather' ),
										'text_off'   => __( 'Hide', 'pearl-weather' ),
										'text_width' => 75,
									),
									array(
										'id'         => 'snow',
										'type'       => 'switcher',
										'title'      => __( 'Snow', 'pearl-weather' ),
										'text_on'    => __( 'Show', 'pearl-weather' ),
										'text_off'   => __( 'Hide', 'pearl-weather' ),
										'text_width' => 75,
									),
								),
							),
							array(
								'id'         => 'forecast_type',
								'class'      => 'pw-forecast-type',
								'type'       => 'button_set',
								'title'      => __( 'Forecast Type', 'pearl-weather' ),
								'options'    => array(
									'hourly' => __( 'Hourly', 'pearl-weather' ),
									'daily'  => __( 'Daily', 'pearl-weather' ),
								),
								'title_info' => '<div class="pw-info-label">' . __( 'Weather Forecast Type', 'pearl-weather' ) . '</div><div class="pw-short-content">' . __( 'Choose between hourly or daily forecasts.', 'pearl-weather' ) . '</div>',
								'default'    => 'hourly',
								'dependency' => array( 'enable_forecast', '==', 'true' ),
							),
							array(
								'id'         => 'forecast_hours',
								'type'       => 'spinner',
								'class'      => 'pw-forecast-hours',
								'title'      => __( 'Forecast Hours', 'pearl-weather' ),
								'unit'       => __( 'Hours', 'pearl-weather' ),
								'max'        => 48,
								'min'        => 1,
								'default'    => 8,
								'title_info' => '<div class="pw-info-label">' . __( 'Number of Forecast Hours', 'pearl-weather' ) . '</div>',
								'dependency' => array( 'enable_forecast|forecast_type', '==|==', 'true|hourly' ),
							),
							array(
								'id'               => 'forecast_icon_type',
								'class'            => 'pw-forecast-icon-type',
								'preview'          => true,
								'type'             => 'select',
								'title'            => __( 'Icon Type', 'pearl-weather' ),
								'options'          => array(
									'icon_set_one'   => __( 'Animated', 'pearl-weather' ),
									'icon_set_two'   => __( 'Static', 'pearl-weather' ),
									'icon_set_three' => __( 'Light Line', 'pearl-weather' ),
									'icon_set_four'  => __( 'Fill', 'pearl-weather' ),
								),
								'default'          => 'icon_set_one',
								'dependency'       => array( 'enable_forecast', '==', 'true' ),
							),
							array(
								'id'         => 'forecast_icon_size',
								'type'       => 'spinner',
								'class'      => 'pw-forecast-icon-size',
								'title'      => __( 'Icon Size', 'pearl-weather' ),
								'unit'       => __( 'px', 'pearl-weather' ),
								'max'        => 300,
								'min'        => 16,
								'default'    => 50,
								'dependency' => array( 'enable_forecast', '==', 'true' ),
							),
							array(
								'id'      => 'forecast_margin',
								'type'    => 'spacing',
								'class'   => 'pw-forecast-margin',
								'title'   => __( 'Margin', 'pearl-weather' ),
								'units'   => array( 'px' ),
								'right'   => false,
								'left'    => false,
								'default' => array(
									'top'    => '0',
									'bottom' => '0',
								),
								'dependency' => array( 'enable_forecast', '==', 'true' ),
							),
							array(
								'type'    => 'notice',
								'style'   => 'info',
								'class'   => 'pw-forecast-notice',
								'content' => sprintf(
									/* translators: %s: upgrade link */
									__( 'To display daily forecasts, advanced carousel options, and more, %sUpgrade to Pro!%s', 'pearl-weather' ),
									'<a href="https://pearlweather.com/pricing/" target="_blank"><strong>',
									'</strong></a>'
								),
							),
						),
					),
					// Tab 6: Footer.
					array(
						'title'  => __( 'Footer', 'pearl-weather' ),
						'icon'   => '<span><i class="pw-icon-footer"></i></span>',
						'fields' => array(
							array(
								'id'         => 'show_detailed_weather',
								'type'       => 'switcher',
								'title'      => __( 'Detailed Weather Link', 'pearl-weather' ),
								'default'    => false,
								'text_on'    => __( 'Show', 'pearl-weather' ),
								'text_off'   => __( 'Hide', 'pearl-weather' ),
								'text_width' => 75,
							),
							array(
								'id'         => 'show_last_update',
								'type'       => 'switcher',
								'title'      => __( 'Last Update Time', 'pearl-weather' ),
								'default'    => false,
								'text_on'    => __( 'Show', 'pearl-weather' ),
								'text_off'   => __( 'Hide', 'pearl-weather' ),
								'text_width' => 75,
							),
							array(
								'id'         => 'show_attribution',
								'type'       => 'switcher',
								'title'      => __( 'Weather Attribution', 'pearl-weather' ),
								'default'    => true,
								'text_on'    => __( 'Show', 'pearl-weather' ),
								'text_off'   => __( 'Hide', 'pearl-weather' ),
								'text_width' => 75,
								'title_info' => '<div class="pw-info-label">' . __( 'Weather Attribution (Copyright)', 'pearl-weather' ) . '</div>',
							),
							array(
								'id'         => 'link_to_source',
								'type'       => 'checkbox',
								'title'      => __( 'Link to Weather Source', 'pearl-weather' ),
								'default'    => false,
								'dependency' => array( 'show_attribution', '==', 'true' ),
							),
							array(
								'id'      => 'footer_margin',
								'type'    => 'spacing',
								'class'   => 'pw-footer-margin',
								'title'   => __( 'Margin', 'pearl-weather' ),
								'units'   => array( 'px' ),
								'right'   => false,
								'left'    => false,
								'default' => array(
									'top'    => '0',
									'bottom' => '0',
								),
							),
						),
					),
				),
			),
		),
	)
);